---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "pip-services-email"
  description: "Email delivery microservice for pip-services"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Performance counters that posts values to log
- descriptor: "pip-services:counters:log:default:1.0"
  level: "trace"

# Default controller
- descriptor: "pip-services-email:controller:default:default:1.0"
  connection:
    service: "{{{EMAIL_SERVICE}}}"
    host: "{{{EMAIL_SERVICE_HOST}}}"
    secure_connection: "{{{EMAIL_SSL}}}"
    port: "{{{EMAIL_SERVICE_PORT}}}"
  credential:
    username: "{{{EMAIL_USER}}}"
    password: "{{{EMAIL_PASS}}}"
  message:
    from: "{{{EMAIL_FROM}}}"
  parameters:
    client_name: "{{{CLIENT_NAME}}}"
    client_url: "{{{CLIENT_URL}}}"
    server_url: "{{{SERVER_URL}}}"
    signature: "{{{EMAIL_SIGNATURE}}}"

# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# HTTP endpoint version 1.0
- descriptor: "pip-services-email:service:http:default:1.0"

# Heartbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"